<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Inicio',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'dlaverde@uniandes.edu.co',
		'to' => 'dlaverde@uniandes.edu.co'
	),
	'fields' => array(
		'custom_U1365' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombres y apellidos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombres y apellidos\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Correo electrónico',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Correo electrónico\' es obligatorio.',
				'format' => 'El campo \'Correo electrónico\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U1411' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Teléfono móvil',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Teléfono móvil\' es obligatorio.'
			)
		),
		'custom_U1994' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Acepto la',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Acepto la\' es obligatorio.'
			)
		),
		'custom_U1670' => array(
			'order' => 4,
			'type' => 'radiogroup',
			'label' => 'Seleccione el posgrado al que quiere aplicar',
			'required' => true,
			'optionItems' => array(
				'Maestría en Biología Computacional',
				'Maestría en Ciencias Biológicas',
				'Maestría en Física',
				'Maestría en Matemáticas',
				'Maestría en Química',
				'Doctorado en Biología',
				'Doctorado en Física',
				'Doctorado en Química'
			),
			'errors' => array(
				'required' => 'El campo \'Seleccione el posgrado al que quiere aplicar\' es obligatorio.',
				'format' => 'El campo \'Seleccione el posgrado al que quiere aplicar\' contiene un valor no válido.'
			)
		)
	)
);

process_form($form);
?>
